// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQR1gOekP4O-xtUKFgzUa5hNDFdbenyJE',
    appId: '1:989424967584:web:9e510e84811532dfc24ec5',
    messagingSenderId: '989424967584',
    projectId: 'mermer-test-basic-81a08',
    authDomain: 'mermer-test-basic-81a08.firebaseapp.com',
    databaseURL: 'https://mermer-test-basic-81a08-default-rtdb.firebaseio.com',
    storageBucket: 'mermer-test-basic-81a08.appspot.com',
    measurementId: 'G-W1ED3VJH42',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJaw_sK0MrSOwpzhIDmJ7sy5agWeFjW88',
    appId: '1:989424967584:android:07a253fb262641bac24ec5',
    messagingSenderId: '989424967584',
    projectId: 'mermer-test-basic-81a08',
    databaseURL: 'https://mermer-test-basic-81a08-default-rtdb.firebaseio.com',
    storageBucket: 'mermer-test-basic-81a08.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT05CuLKZ8OH6yjxxGOUkfIEN4ximQpac',
    appId: '1:989424967584:ios:578c99737719d6bcc24ec5',
    messagingSenderId: '989424967584',
    projectId: 'mermer-test-basic-81a08',
    databaseURL: 'https://mermer-test-basic-81a08-default-rtdb.firebaseio.com',
    storageBucket: 'mermer-test-basic-81a08.appspot.com',
    iosBundleId: 'com.mermer.flutterMermerTestBasic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCT05CuLKZ8OH6yjxxGOUkfIEN4ximQpac',
    appId: '1:989424967584:ios:19e7ebeb047ece77c24ec5',
    messagingSenderId: '989424967584',
    projectId: 'mermer-test-basic-81a08',
    databaseURL: 'https://mermer-test-basic-81a08-default-rtdb.firebaseio.com',
    storageBucket: 'mermer-test-basic-81a08.appspot.com',
    iosBundleId: 'com.mermer.flutterMermerTestBasic.RunnerTests',
  );
}
